function printSegments( segments )

for i = 1:length(segments)
    disp([  'Start_Idx: ', num2str(segments{i}.start_idx),...
            ', End_Idx: ', num2str(segments{i}.end_idx),...
            ', Cluster_Idx: ', num2str(segments{i}.cluster_idx),...
            ', Sim: ', num2str(segments{i}.sim)]);
end